apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: blackduck-hybrid
inputs:
  server-url: 
    description: 'Server URL'
    required: true
  api-token:  
    description: 'API token'
    required: true
  ref:
    description: 'Flag to indicate the ref that should be archived (same as supplied to checkout)'
    required: false
    default: ''
  workspace-dir:
    description: 'Flag to mention the path where the checked out code will be present'
    required: false
    default: ''
  scan-mode:
    description: 'Flag to mention the scan mode'
    required: false
    default: 'INTELLIGENT'
  project-name:
    description: 'Flag to mention the project name'
    required: false
    default: ''
  project-version:
    description: 'Flag to mention the project version'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Generate sha and ref 
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-plugin-chain-utils:c7cbcb9a27d7f75effc0237ae78a96192402d81b
      with:
        entrypoint: assets-plugin-chain-utils
        args: get-commit-info
      env:
        INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
        INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
        INPUT_RUN_ID: ${{ cloudbees.run_id }}
        INPUT_CLOUDBEES_EVENT_PATH: /cloudbees/event.json
        INPUT_REF: ${{ inputs.ref }}
        INPUT_WORKSPACE_DIR: ${{ inputs.workspace-dir }}

    - name: Generate reference files 
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-plugin-chain-utils:c7cbcb9a27d7f75effc0237ae78a96192402d81b
      with:
          entrypoint: assets-plugin-chain-utils
          args: generate-references --asset-type "CODE"
      env:
          INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_RUN_ID: ${{ cloudbees.run_id }}
    - name: Run blackduck compliance plugin
      uses: docker://public.ecr.aws/l7o7z1g8/actions/plugin-blackduck-sca:f3b19960a9fc0d2214b16e2e269adaf3b16a3529
      env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
          BLACKDUCK_URL: ${{ inputs.server-url }}
          BLACKDUCK_API_TOKEN: ${{ inputs.api-token }}
          BLACKDUCK_PROJECT_NAME: ${{ inputs.project-name }}
          BLACKDUCK_PROJECT_VERSION: ${{ inputs.project-version }}
          BLACKDUCK_SCAN_MODE: ${{ inputs.scan-mode }}
      run: /app/plugin-blackduck-scanner -mode single
    - name: Complete execution plan
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-plugin-chain-utils:c7cbcb9a27d7f75effc0237ae78a96192402d81b
      id: process-outputs
      with:
          entrypoint: assets-plugin-chain-utils
          args: process-outputs
      env:
          INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }} 
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_RUN_ID: ${{ cloudbees.run_id }}